// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using AlexandrKondratevKt4120.Database;

#nullable disable

namespace AlexandrKondratevKt4120.Migrations
{
    [DbContext(typeof(DisciplineDbContext))]
    partial class DisciplineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proektniy.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id")
                        .HasComment("Идентификатор дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<int>("DisciplineNagruzka")
                        .HasMaxLength(100)
                        .HasColumnType("int4")
                        .HasColumnName("c_discipline_nagruzka")
                        .HasComment("Нагрузка дисциплины");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_discipline_name")
                        .HasComment("Наименование дисциплины");

                    b.Property<string>("DisciplinePrepod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_discipline_prepod")
                        .HasComment("Преподаватель дисциплины");

                    b.HasKey("DisciplineId")
                        .HasName("pk_(TableName)_DisciplineId");

                    b.ToTable("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
